### ISSUE TITLE
Investigate and use Istio 1.6 CRD Status

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-istio#124]
According to https://istio.io/docs/reference/config/config-status/  Istio CRD Status is now available.

We should investigate and adopt this new feature.

**Comment by tcnghia** [comment]
cc @ZhiminXiang @JRBANCEL @nak3 @therealmitchconnors

**Comment by tcnghia** [comment]
BTW, for backward compatibility with more Istio versions, and this being _alpha_ feature we will probably need to have a feature flag to turn this on.

**Comment by nak3** [comment]
It would be easier to implement this to use VirtualService status only, but it would be great if we can use other CRD's status as pluggable.

For example, Knative on OpenShift uses another CRD(OpenShift Route) as a frontend LB and we want to make sure the OpenShift Route's status before Ksvc ready.

FYI @markusthoemmes

**Comment by markusthoemmes** [comment]
@nak3 thanks for bringing that up but I don't think it'd need to be taken into account here. We kinda need a different design downstream to make that work "properly".

**Comment by JRBANCEL** [comment]
> It would be easier to implement this to use VirtualService status only, but it would be great if we can use other CRD's status as pluggable.
> 
> For example, Knative on OpenShift uses another CRD(OpenShift Route) as a frontend LB and we want to make sure the OpenShift Route's status before Ksvc ready.

I am not sure I understand. In your example, a custom Controller is used (to manage the OpenShift Route), right?
In this case, why does it matter what we do in this repo, specific to Istio?

Anyway, this is blocked because Istio 1.6 populates the `status` field [dynamically](https://github.com/istio/istio/blob/77d9c1040b1a56064f7e59593f53331cca6c7578/pilot/pkg/status/state.go#L195) and the `VirtualService` `struct` doesn't have the field so our generated clients can't consume it cleanly.

@therealmitchconnors what is the issue tracking the work to add the field in 1.7?

**Comment by JRBANCEL** [comment]
We are doing this with Istio 1.7.1.
/assign @arturenault

**Comment by arturenault** [comment]
Istio doesn't have an ObservedGeneration so we have no way of knowing if the Status is current (i.e. if it has applied our latest changes).

This is being tracked in istio/istio#28003. They're attempting to rush it into 1.8 which closes next week, but if not this might need to wait until Istio 1.9.

**Comment by arturenault** [comment]
/unassign JRBANCEL

this is confusing the google github sync
