### ISSUE TITLE
Bug[StatusManager]: Waiting for load balancer to be ready

### ISSUE THREAD

**Issue by haibingzhao** [knative-sandbox/net-istio#245]
When I restart my local kubernetes cluster, and type `kubectl get king`, it always reminder error：`Waiting for load balancer to be ready`

## How to reproduce?
* Install local  kubernetes cluster using [k3d](https://k3d.io/), k3s version is: v1.17.9+k3s1
* Install knative with net-istio
* After install everything is ok
* Now restart local kubernetes cluster: `k3d stop cluster xxx` and `k3d start cluster xxx`
* After a few seconds, type `kubectl get king -oyaml` and get `Waiting for load balancer to be ready` error

## Proposal
I think there might be a race condition in statusManager `IsReady` function.
1. `IsReady` function first cache `ingressStates` with gateway service endpoint ips(when restart k3d cluster, it just return last cached endpoint ips)
2. kubernetes cluster reconciler all resources include gateway service endpoint, and now gateway service endpoint change its ip to now reconciled gateway service pods
3. `statusManager` prob with old ip and get connect error

This will not a problem when deploy kuberneter cluster in production mode. But I think when gateway service pod reconciled, `statusManager` will ignore to prob new gateway service endpoint ips. This bug can be checked manual re-deploy  gateway service deployment, and no new prob logs at `net-istio` log.
What do you think?

**Comment by JRBANCEL** [comment]
I see two somewhat different issues here.

> This bug can be checked manual re-deploy gateway service deployment, and no new prob logs at net-istio log.

This is by design. The idea is that we assume that a new Gateway Pod (Envoy) will always get the latest configuration from Istio, therefore there is no need to probe new Envoy Pods.

> I think there might be a race condition in statusManager `IsReady` function.

statusManager handles the case where a Pod disappears after probing has started and cancels probing for that Pod.
Now, if I understand correctly what you are saying, the endpoint lister returns outdated Pod IPs, which is fine, but we never get the signal that those Pods have disappeared. We rely on Kubernetes to tell us a Pod has been deleted. We don't go further than that. 

Can the Pod deletion signal arrive before we start probing? Yes, that's possible. Maybe we should handle this by periodically checking if the Pods being probed still exist.
