### ISSUE TITLE
DomainMapping exposes the cluster-local knative service to the public

### ISSUE THREAD

**Issue by ZhiminXiang** [knative-sandbox/net-istio#566]
- Expected behavior:
After creating a domainmapping to map a custom domain to a cluster-local service, the domainmapping should only be effective within the cluster. The knative service should not be accessible from outside of the cluster.
Note: this is my personal understanding. We could also disallow creating DomainMapping to a cluster local service. At least I don't think we should expose cluster-local service to public through DomainMapping

- Actual behavior:
After creating a DomainMapping to map to a cluster-local service, the service is able to be accessed by using the custom domain from outside of the cluster.

/cc @julz

**Comment by julz** [comment]
Hm. This is working as designed. If you create a domain mapping you are creating an external name for the service and exposing it. You may want to point a DM at a cluster local service for example if you only want to expose the fancy name and not the auto generated one foo.myns.mydomain one. Since the user explicitly creates the DM, and only DMs within a target in the same namespace are supported, I don't think DMs can expose a service outside a ns a user controls?

**Comment by nak3** [comment]
I also think this is expected design.
As julz mentioned, the cluster-local ksvc could be exposed but it is done by a user controls, so it should be no problem.

**Comment by ZhiminXiang** [comment]
OK this sounds fair. I created a PR to explicitly point it out in our doc https://github.com/knative/docs/pull/3704
