### ISSUE TITLE
Support individual Ingress's HTTPOption

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#637]
https://github.com/knative/networking/issues/301 tries to allow a specific Ingress to change http option but current net-istio uses one http server globally with `*`

https://github.com/knative-sandbox/net-istio/blob/ab9dfc86f07f3ce0da06f3cc42282fcf2e0ad82c/config/202-gateway.yaml#L27-L33

So one Ingress's HTTPOption effects on all HTTP behavior. In other words, net-istio have to use same HTTPOption within a cluster.

**Comment by ZhiminXiang** [comment]
For the short term to support the backward compatibility, we can do the following works:
1. the global Gateway `knative-ingress-gateway` with HTTP protocol could be considered as the default Gateway when Kingress HTTPOption is HTTP. That is, all HTTP Kingress will be tied to the global Gateway.
2. When Kingress HTTPOption is not HTTP (e.g. HTTPS), we create a Kingress specific Gateway, and tie the Kingress to the Gateway.
This is what we are currently doing when auto-TLS is enabled.

For the long term, we could consider getting rid of the global Gateway (but TBH this could be difficult because in our current instructions we use the global Gateway as the API to manually configure TLS at this point).
